config/routes.rb
Rails.application.routes.draw do
  resources :validates
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/validate.rb
class Validate < ApplicationRecord
    validates :Firstname, presence: true
    validates :password, confirmation: true,presence: true
    validates :Number, format: { with: /\A\d+\Z/,message: "only allows number" },presence: true
    validates :email, format: { with: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/},presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/validates_controller.rb
class ValidatesController < ApplicationController
  def index
    @alldata=Validate.all

  end

  def new
    @info=Validate.new
  end

  def create()
    @info = Validate.new(validate_params)
    @info.save
   if @info.save

    index
    render 'index'

   else
    render 'new'
   end
    
    
  end
  
private
def validate_params  
params.require(:validate).permit(:Firstname,:Lastname,:Bdate,:Address,:City,:State,:Contry,:Hobby,:Companyname,:Employeid,:Number,:email,:password,:password_confirmation)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/validates_helper.rb
module ValidatesHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
   
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Validation</title>
  </head>
  <body>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/validates/index.html.erb
<%if flash[:notice]%>
<div class="alert alert-success" role="alert" style="text-align:center">
  <%= flash[:notice]%>
</div>
<%end%>

<%=link_to "Insert Data", new_validate_path %><br><hr>
<%@alldata.each do |data|%>
First Name  ::<%=data.Firstname%><br>
Last Name  ::<%=data.Lastname%><br>

Birth Date  ::<%=data.Bdate%><br>
City  ::<%=data.City%><br>
State  ::<%=data.State%><br>
Contry  ::<%=data.Contry%><br>
Hobby  ::<%=data.Hobby%><br>
Company Name  ::<%=data.Companyname%><br>
Employe id  ::<%=data.Employeid%><br>
Email  ::<%=data.email%><br>
phone number  ::<%=data.Number%><br>
<hr>
<%end%>

app/views/validates/new.html.erb
<%if flash[:notice]%>
<div class="alert alert-success" role="alert" style="text-align:center">
  <%= flash[:notice]%>
</div>
<%end%>
<div style="height:900px;width:90%;margin-left:5%">
  <center><h1>Personal Information</h1><br></center>
  <%= form_for @info, url:validates_path,method:'post' do |f| %>
  
  <div class="row g-2">
    <div class="col-sm">
      First Name *<%=f.text_field :Firstname,class:"form-control"%>
      <div class="error_msg"><%=@info.errors[:Firstname].to_sentence%><br><br></div>
    </div>
    <div class="col-sm">
      Last Name<%=f.text_field :Lastname,class:"form-control"%><br><br>
    </div>
  </div>
  
  
  
  Birth Date<%=f.date_field :Bdate,class:"form-control"%><br><br>
  Address<%=f.text_area :Address,class:"form-control"%><br><br>
  City<%=f.text_field :City,class:"form-control"%><br><br>
  State<%=f.text_field :State,class:"form-control"%><br><br>
  Contry<%=f.text_field :Contry,class:"form-control"%><br><br>
  Hobby<%=f.text_field :Hobby,class:"form-control"%><br><br><br>
  
  <center><h1>Professional Information</h1><br></center>
  
  Comapanyname<%=f.text_field :Companyname,class:"form-control"%><br><br>
  Number<%=f.text_field :Number,class:"form-control"%>
  <div class="error_msg"><%=@info.errors[:Number].to_sentence%></div><br><br>
  Employeid<%=f.text_field :Employeid,class:"form-control"%><br><br>
  Email<%=f.text_field :email,class:"form-control"%>
  <div class="error_msg"><%=@info.errors[:email].to_sentence%><br><br></div>
  Password<%=f.text_field :password,class:"form-control"%>
  <div class="error_msg">
  <%=@info.errors[:password].to_sentence%></div><br><br>
  Re-Enter Password<%=f.text_field :password_confirmation,class:"form-control"%>
  <div class="error_msg">
  <%=@info.errors[:password_confirmation].to_sentence%></div><br><br>
  <div>
    <p>Please check your data before submit</p>
  <%=f.check_box :conform,class:"form-check-input"%>
  </div>
  <%=f.submit "Submit",class:"btn btn-primary"%>
  <%end%>
</div>